name: 'Veracode DAST Essentials Action'
description: 'A Github Action for Running a Veracode DAST Essentials scan to perform Dynamic Application Security Testing (DAST).'
branding:
  icon: 'alert-triangle'
  color: 'red'
inputs:
  VERACODE_WEBHOOK:
    description: 'Webhook Secret of the DAST Essentials Scan Target'
    required: true
  VERACODE_SECRET_ID:
    description: 'API Secret ID of the DAST Essentials Scan Target'
    required: true
  VERACODE_SECRET_ID_KEY:
    description: 'API Secret ID Key of the DAST Essentials Scan Target'
    required: true
  REGION:
    description: 'Region of the DAST Essentials'
    required: false
    default: 'us'
  PROXY_URL:
    description: 'Proxy URL'
    required: false
    default: ''
  pull-report:
    description: 'Flag whether the report should be downloaded as JUnit XML file'
    required: false
    default: 'false'
runs:
  using: 'node12'
  main: 'index.js'
